In [1]:
import pandas as pd
import pymongo
from rich.console import Console

console = Console()

mongoClient = pymongo.MongoClient("localhost", 27017)

In [23]:
List_HNX30 : list = ["CAP","CEO","DHT","DTD","DVM","DXP","HLD","HUT","IDC","IDV"
     ,"L14","L18","LAS","LHC","MBS","NTP","NVB","PLC","PSD","PVB"
    ,"PVC","PVS","SHS","SLS","TIG","TMB","TNG","TVD","VC3","VCS"]

In [5]:
coll = mongoClient["test-database"]["test-collection"]

data = pd.DataFrame(list(coll.find({ 'id': 3220})))
data

,_id,id,sym,lastPrice,lastVol,cl,change,changePc,totalVol,time,...,ch,lp,lc,ap,ca,timeServer,sID,lv,openPrice,side
0,676c05151f8f9d92a0735314,3220,CEO,14.0,900,f,1.50,9.68,900,09:00:01,...,d,14.0,f,14.1,d,09:00:01,260720240804311,300,0,B
1,676c05151f8f9d92a073531f,3220,HUT,16.4,50,d,0.20,1.20,50,09:00:02,...,d,16.4,d,16.4,d,09:00:02,260720240804313,50,0,S
2,676c05151f8f9d92a073534a,3220,SHS,16.6,40,e,0.00,0.00,40,09:00:03,...,e,16.6,e,16.6,e,09:00:03,2607202408043111,20,0,S
3,676c05151f8f9d92a073537e,3220,CEO,15.6,20,i,0.10,0.65,920,09:00:05,...,i,14.0,f,14.1,d,09:00:05,2607202408043123,10,0,B
4,676c05151f8f9d92a07353a7,3220,TNG,24.5,10,e,0.00,0.00,10,09:00:06,...,e,24.5,e,24.5,e,09:00:06,2607202408043127,10,0,S
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7631,676c05161f8f9d92a073e7e5,3220,DVM,10.8,100,i,0.20,1.89,36590,14:52:50,...,i,10.4,d,10.6,e,14:52:50,2607202408043128618,100,0,BS
7632,676c05161f8f9d92a073e7ea,3220,DVM,10.8,300,i,0.20,1.89,36890,14:54:04,...,i,10.4,d,10.6,e,14:54:04,2607202408043128698,300,0,BS
7633,676c05161f8f9d92a073e7ed,3220,PVS,41.8,200,i,0.80,1.95,254140,14:54:34,...,i,40.8,d,41.3,i,14:54:34,2607202408043128734,200,0,BS
7634,676c05161f8f9d92a073e7f1,3220,HUT,16.8,20,i,0.20,1.20,79700,14:56:19,...,i,16.4,d,16.7,i,14:56:19,2607202408043128863,20,0,BS
7635,676c05161f8f9d92a073e7f7,3220,HUT,16.8,30,i,0.20,1.20,79730,14:57:44,...,i,16.4,d,16.7,i,14:57:44,2607202408043128977,30,0,BS

In [30]:
tt = list()
listsym = dict()
listVol = dict()


for sym in List_HNX30:
    listsym.update({sym: 0.0})
    listVol.update({sym: 0})
df = pd.DataFrame(list(coll.find({'id': 3220}))).loc[ : , ['sym', 'lastVol', 'lastPrice', 'timeServer'] ]

point : float = 0.0

totalVol : int = 0

for val in df.values:
    totalVol += val[1]
    
    point += float(val[2]) - listsym[val[0]]
    point = round(point,1)
    listsym[val[0]] = val[2]
    
    listVol[val[0]] += val[1]